package Working;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Nithin Nayak
 */
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

public class AdminEntry extends javax.swing.JFrame {

    /**
     * Creates new form AdminEntry
     */
    public AdminEntry() {
        initComponents();
       
  

    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        head = new javax.swing.JLabel();
        houtype = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        hadd = new javax.swing.JTextField();
        harea = new javax.swing.JTextField();
        hid = new javax.swing.JTextField();
        hloc = new javax.swing.JTextField();
        hbuild = new javax.swing.JTextField();
        hyoc = new javax.swing.JTextField();
        hgp = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        htype = new javax.swing.JTextField();
        houtype2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        head2 = new javax.swing.JLabel();
        houtype3 = new javax.swing.JLabel();
        dhlabel = new javax.swing.JTextField();
        add2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        head.setBackground(new java.awt.Color(0, 204, 102));
        head.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        head.setForeground(new java.awt.Color(255, 255, 255));
        head.setText("                      Enter Property Details");
        head.setOpaque(true);
        jPanel1.add(head, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 50));

        houtype.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        houtype.setForeground(new java.awt.Color(255, 255, 255));
        houtype.setText("House ID :");
        jPanel1.add(houtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 130, 40));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Area (in sq ft)   : ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 210, 40));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Location  : ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 130, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Builder Group : ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 190, 50));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Year of Construction :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 230, 50));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Guarantee period  :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 210, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Address : ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, 130, 30));

        hadd.setBackground(new java.awt.Color(204, 255, 204));
        hadd.setFont(new java.awt.Font("Imprint MT Shadow", 0, 24)); // NOI18N
        jPanel1.add(hadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 490, 400, 40));

        harea.setBackground(new java.awt.Color(204, 255, 204));
        harea.setFont(new java.awt.Font("Imprint MT Shadow", 0, 24)); // NOI18N
        harea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hareaActionPerformed(evt);
            }
        });
        jPanel1.add(harea, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 400, 40));

        hid.setBackground(new java.awt.Color(204, 255, 204));
        hid.setFont(new java.awt.Font("Imprint MT Shadow", 0, 24)); // NOI18N
        hid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hidActionPerformed(evt);
            }
        });
        jPanel1.add(hid, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 400, 40));

        hloc.setBackground(new java.awt.Color(204, 255, 204));
        hloc.setFont(new java.awt.Font("Imprint MT Shadow", 0, 24)); // NOI18N
        jPanel1.add(hloc, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 400, 40));

        hbuild.setBackground(new java.awt.Color(204, 255, 204));
        hbuild.setFont(new java.awt.Font("Imprint MT Shadow", 0, 24)); // NOI18N
        jPanel1.add(hbuild, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 400, 40));

        hyoc.setBackground(new java.awt.Color(204, 255, 204));
        hyoc.setFont(new java.awt.Font("Imprint MT Shadow", 0, 24)); // NOI18N
        jPanel1.add(hyoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 400, 40));

        hgp.setBackground(new java.awt.Color(204, 255, 204));
        hgp.setFont(new java.awt.Font("Imprint MT Shadow", 0, 24)); // NOI18N
        jPanel1.add(hgp, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 400, 40));

        add.setBackground(new java.awt.Color(0, 204, 102));
        add.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setText("Feed Details");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 560, 570, 60));

        htype.setBackground(new java.awt.Color(204, 255, 204));
        htype.setFont(new java.awt.Font("Imprint MT Shadow", 0, 24)); // NOI18N
        htype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                htypeActionPerformed(evt);
            }
        });
        jPanel1.add(htype, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 400, 40));

        houtype2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        houtype2.setForeground(new java.awt.Color(255, 255, 255));
        houtype2.setText("House Type: ");
        jPanel1.add(houtype2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 160, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 710, 640));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(255, 255, 0));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton2.setText("Go for allotment");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 610, 70));

        jButton4.setBackground(new java.awt.Color(255, 255, 0));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton4.setText("Show Houses List");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 610, 70));

        jButton5.setBackground(new java.awt.Color(255, 255, 0));
        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton5.setText("Show Applicant List");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 610, 70));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 360, 700, 380));

        jLabel3.setBackground(new java.awt.Color(255, 204, 0));
        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 50)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("                    A D M I N   P A N E  L");
        jLabel3.setToolTipText("");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 1080, 90));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        head2.setBackground(new java.awt.Color(0, 204, 102));
        head2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        head2.setForeground(new java.awt.Color(255, 255, 255));
        head2.setText("                           Delete Property Details");
        head2.setOpaque(true);
        jPanel3.add(head2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 50));

        houtype3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        houtype3.setForeground(new java.awt.Color(255, 255, 255));
        houtype3.setText("House ID :");
        jPanel3.add(houtype3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 170, 50));

        dhlabel.setBackground(new java.awt.Color(204, 255, 204));
        dhlabel.setFont(new java.awt.Font("Imprint MT Shadow", 0, 24)); // NOI18N
        dhlabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dhlabelActionPerformed(evt);
            }
        });
        jPanel3.add(dhlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 480, 50));

        add2.setBackground(new java.awt.Color(255, 0, 0));
        add2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        add2.setForeground(new java.awt.Color(255, 255, 255));
        add2.setText("Delete");
        add2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add2ActionPerformed(evt);
            }
        });
        jPanel3.add(add2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 180, 50));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 110, 800, 260));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Working/formbg.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1630, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
try{ 
        Class.forName("com.mysql.cj.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/maindb", "root", "");
     String sql = "INSERT INTO housedetail(did, darea, dloc,dbuilder, dyoc, dgp,dadd, ttype) VALUES (?,?,?,?,?,?,?, ?)";
String houid = hid.getText();
String type = htype.getText();
String area = harea.getText();
String location = hloc.getText();
String builder = hbuild.getText();
String yearOfConstruction = hyoc.getText();
String address = hadd.getText();
String gpp = hgp.getText();

PreparedStatement psmt = con.prepareStatement(sql);

    // Set values for the placeholders
    psmt.setString(1, houid);
    psmt.setString(2, area);
    psmt.setString(3, location);
    psmt.setString(4, builder);
    psmt.setString(5, yearOfConstruction);
    psmt.setString(6, gpp);
    psmt.setString(7, address);
    psmt.setString(8, type);
    
    // Execute the INSERT statement and get the number of rows affected
    int rowsAffected = psmt.executeUpdate();
     if (rowsAffected > 0) {
        JOptionPane.showMessageDialog(this, "Details registered successfully.");
         hid.setText("");
        htype.setText("");
        harea.setText("");
        hgp.setText("");
        hbuild.setText("");
        hloc.setText("");
        hyoc.setText("");
        hadd.setText("");
    } else {
        JOptionPane.showMessageDialog(this, "Failed to register details.");
    }

    // Close the prepared statement and the database connection in a finally block
    psmt.close();
    con.close();
} catch(Exception e) {
   System.out.println(e.getMessage());
} 






// Clear the text fields after adding data

    }//GEN-LAST:event_addActionPerformed

    private void hareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hareaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hareaActionPerformed

    private void hidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hidActionPerformed

    private void htypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_htypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_htypeActionPerformed

    private void dhlabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dhlabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dhlabelActionPerformed

    private void add2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add2ActionPerformed
       try {
            Class.forName("com.mysql.cj.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/maindb", "root", "");
     String sql = "DELETE FROM housedetail WHERE did = ?";
     String douid = dhlabel.getText();
     PreparedStatement psmt = con.prepareStatement(sql);

    // Set values for the placeholders
    psmt.setString(1, douid);
     int rowsAffected = psmt.executeUpdate();
     if (rowsAffected > 0) {
        JOptionPane.showMessageDialog(this, "Details removed successfully.");
         dhlabel.setText("");
     }else {
        JOptionPane.showMessageDialog(this, "Failed to delete details.");
    }

    // Close the prepared statement and the database connection in a finally block
    psmt.close();
    con.close();
       }
       catch(Exception e) {
   System.out.println(e.getMessage());
} 
    }//GEN-LAST:event_add2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ALLOT alot = new ALLOT();
        alot.show();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        HouseDetails hdd = new HouseDetails();
        hdd.show();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        ApplicantListing app = new ApplicantListing();
        app.show();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminEntry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton add2;
    private javax.swing.JTextField dhlabel;
    private javax.swing.JTextField hadd;
    private javax.swing.JTextField harea;
    private javax.swing.JTextField hbuild;
    private javax.swing.JLabel head;
    private javax.swing.JLabel head2;
    private javax.swing.JTextField hgp;
    private javax.swing.JTextField hid;
    private javax.swing.JTextField hloc;
    private javax.swing.JLabel houtype;
    private javax.swing.JLabel houtype2;
    private javax.swing.JLabel houtype3;
    private javax.swing.JTextField htype;
    private javax.swing.JTextField hyoc;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
