/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Working;

import javax.swing.JOptionPane;

/**
 *
 * @author Himanshu
 */
import java.sql.*;
import javax.swing.*;

public class CardPayment extends javax.swing.JFrame {
public String pppname,pppdob,pppuid,pppadd,pppphone, pppemail;
    /**
     * Creates new form CardPayment
     */
    public CardPayment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cardno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pay = new javax.swing.JButton();
        cvv = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 102));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Card Payment");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(168, 168, 168))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 527, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pay using your Card :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 107, 197, 51));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(" Debit Card");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 254, 51));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Enter Card Number :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 176, 197, 44));

        cardno.setBackground(new java.awt.Color(204, 255, 204));
        cardno.setFont(new java.awt.Font("Imprint MT Shadow", 0, 24)); // NOI18N
        getContentPane().add(cardno, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 176, 268, 40));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Enter Card CVV      :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 249, 190, 41));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Amount                     :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 308, 190, 30));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("₹ 25000/-");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 308, 87, 30));

        pay.setBackground(new java.awt.Color(0, 204, 102));
        pay.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        pay.setForeground(new java.awt.Color(255, 255, 255));
        pay.setText("Pay");
        pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payActionPerformed(evt);
            }
        });
        getContentPane().add(pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 183, 53));

        cvv.setBackground(new java.awt.Color(204, 255, 204));
        cvv.setFont(new java.awt.Font("Imprint MT Shadow", 0, 24)); // NOI18N
        getContentPane().add(cvv, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 80, 30));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Working/formbg.jpg"))); // NOI18N
        jLabel8.setOpaque(true);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 6, 530, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payActionPerformed
try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bank", "root", "");
    String cardnum = cardno.getText();
    String cv = cvv.getText();
    
    String sql = "SELECT * FROM carddetails WHERE card_number = ? AND cvv = ?";
    PreparedStatement pstmt = con.prepareStatement(sql);
    pstmt.setString(1, cardnum);
    pstmt.setString(2, cv);
    
    String cut = "SELECT Account_Number FROM carddetails WHERE card_number = ?";
    PreparedStatement ps = con.prepareStatement(cut);
    ps.setString(1, cardnum);
    
    ResultSet rs = pstmt.executeQuery();
    ResultSet rss = ps.executeQuery();
    
    if (rs.next() && rss.next()) {
        JOptionPane.showMessageDialog(this, "Payment Successful. Click OK to proceed towards Lottery Number Generation");
        int accountNumber = rss.getInt("Account_Number");
        
        // Update the account balance
        String finred = "UPDATE accountdetails SET Account_balance = Account_balance -25000 WHERE Account_Number = ?";
        PreparedStatement pre = con.prepareStatement(finred);
        pre.setInt(1, accountNumber);
        pre.executeUpdate(); // Execute the update query
        
        String cred = "UPDATE carddetails SET Account_balance = Account_balance -25000 WHERE Account_Number = ?";
        PreparedStatement prep = con.prepareStatement(cred);
        prep.setInt(1, accountNumber);
        prep.executeUpdate(); // Execute the update query
        
        String ured = "UPDATE upidetails SET Account_balance = Account_balance -25000 WHERE Account_Number = ?";
        PreparedStatement prepa = con.prepareStatement(ured);
        prepa.setInt(1, accountNumber);
        prepa.executeUpdate(); // Execute the update query
        
        StaffLogin2 lot = new StaffLogin2();
        lot.finalname = pppname;
        lot.finaluid = pppuid;
        lot.finaldob = pppdob;
        lot.finaladd = pppadd;
        lot.finalphone = pppphone;
        lot.finalemail = pppemail;
        lot.show();
        this.dispose();
    } else {
        JOptionPane.showMessageDialog(this, "Payment Failed. Try Again");
        PaymentOption payop = new PaymentOption();
        payop.show();
        this.dispose();
    }
    
    rs.close();
    pstmt.close();
    rss.close();
    ps.close();
    con.close();
} catch (Exception e) {
    System.out.println(e.getMessage());
}


    }//GEN-LAST:event_payActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CardPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CardPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CardPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CardPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CardPayment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cardno;
    private javax.swing.JPasswordField cvv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton pay;
    // End of variables declaration//GEN-END:variables
}
