/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Working;

/**
 *
 * @author Himanshu
 */
import javax.swing.*;
import java.sql.*;
public class Homepage extends javax.swing.JFrame {

    /**
     * Creates new form Homepage
     */
    public Homepage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 600), new java.awt.Dimension(0, 600), new java.awt.Dimension(32767, 600));
        ulog = new javax.swing.JButton();
        slog = new javax.swing.JButton();
        uregister = new javax.swing.JButton();
        checkallot = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1496, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 0, -1, -1));

        ulog.setBackground(new java.awt.Color(0, 0, 51));
        ulog.setFont(new java.awt.Font("Rockwell", 1, 30)); // NOI18N
        ulog.setForeground(new java.awt.Color(255, 255, 255));
        ulog.setText("USER LOGIN");
        ulog.setBorder(null);
        ulog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ulogActionPerformed(evt);
            }
        });
        getContentPane().add(ulog, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 410, 80));

        slog.setBackground(new java.awt.Color(0, 0, 51));
        slog.setFont(new java.awt.Font("Rockwell", 1, 30)); // NOI18N
        slog.setForeground(new java.awt.Color(255, 255, 255));
        slog.setText("STAFF LOGN");
        slog.setBorder(null);
        slog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slogActionPerformed(evt);
            }
        });
        getContentPane().add(slog, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 460, 410, 80));

        uregister.setBackground(new java.awt.Color(0, 0, 51));
        uregister.setFont(new java.awt.Font("Rockwell", 1, 30)); // NOI18N
        uregister.setForeground(new java.awt.Color(255, 255, 255));
        uregister.setText("REGISTER");
        uregister.setBorder(null);
        uregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uregisterActionPerformed(evt);
            }
        });
        getContentPane().add(uregister, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 580, 410, 80));

        checkallot.setBackground(new java.awt.Color(0, 0, 51));
        checkallot.setFont(new java.awt.Font("Rockwell", 1, 28)); // NOI18N
        checkallot.setForeground(new java.awt.Color(255, 255, 255));
        checkallot.setText("CHECK YOUR ALLOTMENT");
        checkallot.setBorder(null);
        checkallot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkallotActionPerformed(evt);
            }
        });
        getContentPane().add(checkallot, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 580, 410, 80));

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 80)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TOMORROW, built today");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 1060, 140));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("\" HomeMatch : Where Dreams Find Thier Address\"");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Working/logo .png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 40, 350, 230));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("HOUSING ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("LOTTERY SYSTEM");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 230, -1, -1));

        jLabel6.setFont(new java.awt.Font("Serif", 2, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("We Don't build Houses, ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 690, -1, -1));

        jLabel7.setFont(new java.awt.Font("Serif", 2, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("We build Dreams !");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 690, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Working/bgfinal (2).jpg"))); // NOI18N
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -170, 1500, 1020));

        jMenuBar1.setBackground(new java.awt.Color(153, 153, 153));
        setJMenuBar(jMenuBar1);
    }// </editor-fold>//GEN-END:initComponents

    private void ulogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ulogActionPerformed
        loginpage l = new loginpage();
        l.show();
    }//GEN-LAST:event_ulogActionPerformed

    private void slogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slogActionPerformed
        StaffLogin sl = new StaffLogin();
        sl.show();
    }//GEN-LAST:event_slogActionPerformed

    private void checkallotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkallotActionPerformed
       CheckAllotment cl = new CheckAllotment();
       cl.show(); 
    }//GEN-LAST:event_checkallotActionPerformed

    private void uregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uregisterActionPerformed
       Register r = new Register();
        r.show();
    }//GEN-LAST:event_uregisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkallot;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton slog;
    private javax.swing.JButton ulog;
    private javax.swing.JButton uregister;
    // End of variables declaration//GEN-END:variables
}
