/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Working;

/**
 *
 * @author Himanshu
 */
import java.sql.*;
import java.util.HashSet;
import java.util.Random;
import java.util.Set;
import java.awt.*;
import javax.swing.*;


import javax.swing.*;
public class StaffLogin2 extends javax.swing.JFrame {
    public String finalname;
    public String finaluid;
    public String finaldob;
    public String finaladd;
    public String finalphone;
    public String finalemail;

   
    public StaffLogin2() {
        initComponents();
    }
    public static String generateUniqueRandomNumber(int numberOfDigits) {
        if (numberOfDigits < 1) {
            throw new IllegalArgumentException("Number of digits must be at least 1");
        }

        // Calculate the minimum and maximum values for the specified number of digits
        int min = (int) Math.pow(10, numberOfDigits - 1);
        int max = (int) Math.pow(10, numberOfDigits) - 1;

        Random random = new Random();
        Set<String> generatedNumbers = new HashSet<>();

        while (true) {
            int randomNumber = random.nextInt(max - min + 1) + min;
            String randomUniqueNumber = String.format("%0" + numberOfDigits + "d", randomNumber);

            if (!generatedNumbers.contains(randomUniqueNumber)) {
                // This number is unique
                generatedNumbers.add(randomUniqueNumber);
                return randomUniqueNumber;
            }
        }
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        genlot = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lotno = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ch = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jButton1.setBackground(new java.awt.Color(0, 255, 204));
        jButton1.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jButton1.setText("Generate Lottery Number");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Your Lottery no is :");

        jTextField1.setBackground(new java.awt.Color(153, 204, 255));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        genlot.setBackground(new java.awt.Color(0, 204, 102));
        genlot.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        genlot.setForeground(new java.awt.Color(255, 255, 255));
        genlot.setText("Generate Lottery Number");
        genlot.setBorder(new javax.swing.border.MatteBorder(null));
        genlot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genlotActionPerformed(evt);
            }
        });
        getContentPane().add(genlot, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 340, 80));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Your Lottery no is :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 190, 50));

        lotno.setEditable(false);
        lotno.setBackground(new java.awt.Color(204, 255, 204));
        lotno.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        lotno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lotnoActionPerformed(evt);
            }
        });
        getContentPane().add(lotno, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 300, 50));

        jPanel1.setBackground(new java.awt.Color(0, 204, 102));

        jLabel4.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Let's generate your Lucky Number");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 60));

        ch.setBackground(new java.awt.Color(0, 204, 102));
        ch.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        ch.setForeground(new java.awt.Color(255, 255, 255));
        ch.setText("Save details");
        ch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chActionPerformed(evt);
            }
        });
        getContentPane().add(ch, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 180, 40));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Working/formbg.jpg"))); // NOI18N
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 510, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lotnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lotnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lotnoActionPerformed

    private void genlotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genlotActionPerformed
         int numberOfDigits = 7;
        String randomUniqueNumber = generateUniqueRandomNumber(numberOfDigits);
       
        lotno.setText(randomUniqueNumber);
        genlot.setEnabled(false);
    }//GEN-LAST:event_genlotActionPerformed

    private void chActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chActionPerformed
               try {
    // Load the MySQL JDBC driver
    Class.forName("com.mysql.cj.jdbc.Driver");

    // Establish a database connection
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/maindb", "root", "");

    // Define the SQL query with placeholders
    String sql = "INSERT INTO finaldetails(Finuid, Finname, Findob, Finadd, Finphone, Finemail, Lotno) VALUES (?,?,?,?,?,?,?)";
    
    

    // Create a prepared statement
    PreparedStatement psmt = con.prepareStatement(sql);

    // Set values for the placeholders
    psmt.setString(1, finaluid);
    psmt.setString(2, finalname);
    psmt.setString(3, finaldob);
    psmt.setString(4, finaladd);
    psmt.setString(5, finalphone);
    psmt.setString(6, finalemail);
    
    String lotte = lotno.getText();
    psmt.setString(7, lotte);
    
    // Execute the INSERT statement and get the number of rows affected
    int rowsAffected = psmt.executeUpdate();
    sql = "INSERT INTO registereduid  VALUES (?)";
    PreparedStatement psmtt = con.prepareStatement(sql);
    psmtt.setString(1, finaluid);
    int rowsAffectedd = psmtt.executeUpdate();
    
    
    

    if (rowsAffected > 0) {
        JOptionPane.showMessageDialog(this, "Details registered successfully.");
         closeAllWindows();
        Homepage h = new Homepage();
        h.show();
        
    } else {
        JOptionPane.showMessageDialog(this, "Failed to register details.");
    }

    // Close the prepared statement and the database connection in a finally block
    psmt.close();
    con.close();
    
} catch(Exception e) {
   System.out.println(e.getMessage());
} 

    }//GEN-LAST:event_chActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        
    
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffLogin2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffLogin2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffLogin2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffLogin2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffLogin2().setVisible(true);
            }
        });
    }
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ch;
    private javax.swing.JButton genlot;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField lotno;
    // End of variables declaration//GEN-END:variables

    void setFinalName(String bname) {
    }

    void setFinalUid(String buid) {
    }

    void setFinalDob(String bdob) {
    }

    void setFinalAdd(String baddress) {
    }

    private void closeAllWindows() {
        
    }
}
