/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Working;


import java.sql.*;
import javax.swing.*;

/**
 *
 * @author Himanshu
 */
public class UpiPayment extends javax.swing.JFrame {
public String pppname,pppdob,pppuid,pppadd,pppphone, pppemail;
    /**
     * Creates new form UpiPayment
     */
    public UpiPayment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        UPINO = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        UPIN = new javax.swing.JPasswordField();
        UPAY = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 102));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("UPI Payment");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(161, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 516, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter Your UPI ID :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 138, 182, 62));

        UPINO.setBackground(new java.awt.Color(204, 255, 204));
        getContentPane().add(UPINO, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 145, 239, 50));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Enter UPI  Pin        :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 180, 42));

        UPIN.setBackground(new java.awt.Color(204, 255, 204));
        UPIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPINActionPerformed(evt);
            }
        });
        getContentPane().add(UPIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 240, 127, 45));

        UPAY.setBackground(new java.awt.Color(0, 204, 102));
        UPAY.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        UPAY.setForeground(new java.awt.Color(255, 255, 255));
        UPAY.setText("Pay");
        UPAY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPAYActionPerformed(evt);
            }
        });
        getContentPane().add(UPAY, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 350, 118, 47));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Amount                    :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 308, 190, 30));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("₹ 25000/-");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 308, 87, 30));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Working/formbg.jpg"))); // NOI18N
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 6, 510, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UPINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UPINActionPerformed

    private void UPAYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPAYActionPerformed
      try{ 
        Class.forName("com.mysql.cj.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bank", "root", "");
   
    String sql = "SELECT * FROM upidetails WHERE upiid = ? AND pin = ?";
    String up = UPINO.getText();
    String pp = UPIN.getText();
    PreparedStatement pstmt = con.prepareStatement(sql);
    pstmt.setString(1, up);
    pstmt.setString(2, pp);
    
     String cut = "SELECT Account_Number FROM upidetails WHERE upiid = ?";
    PreparedStatement ps = con.prepareStatement(cut);
    ps.setString(1, up);
    
    ResultSet rs = pstmt.executeQuery();
    ResultSet rss = ps.executeQuery();
    
    if (rs.next() && rss.next()) {
        JOptionPane.showMessageDialog(this, "Payment Successful. Click OK to proceed towards Lottery Number Generation");
        int accountNumber = rss.getInt("Account_Number");
        
        // Update the account balance
        String finred = "UPDATE accountdetails SET Account_balance = Account_balance -25000 WHERE Account_Number = ?";
        PreparedStatement pre = con.prepareStatement(finred);
        pre.setInt(1, accountNumber);
        pre.executeUpdate(); // Execute the update query
        
        String cred = "UPDATE carddetails SET Account_balance = Account_balance -25000 WHERE Account_Number = ?";
        PreparedStatement prep = con.prepareStatement(cred);
        prep.setInt(1, accountNumber);
        prep.executeUpdate(); // Execute the update query
        
        String ured = "UPDATE upidetails SET Account_balance = Account_balance -25000 WHERE Account_Number = ?";
        PreparedStatement prepa = con.prepareStatement(ured);
        prepa.setInt(1, accountNumber);
        prepa.executeUpdate(); // Execute the update query
        
        StaffLogin2 lot = new StaffLogin2();
        lot.finalname = pppname;
        lot.finaluid = pppuid;
        lot.finaldob = pppdob;
        lot.finaladd = pppadd;
        lot.finalphone = pppphone;
        lot.finalemail = pppemail;
        lot.show();
        this.dispose();
    } else {
        JOptionPane.showMessageDialog(this, "Payment Failed. Try Again");
        PaymentOption payop = new PaymentOption();
        payop.show();
        this.dispose();
    }
    
    rs.close();
    pstmt.close();
    rss.close();
    ps.close();
    con.close();
} catch (Exception e) {
    System.out.println(e.getMessage());
}

    }//GEN-LAST:event_UPAYActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpiPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpiPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpiPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpiPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpiPayment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton UPAY;
    private javax.swing.JPasswordField UPIN;
    private javax.swing.JTextField UPINO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
